### ISSUE TITLE
searching for items does not find items in guild bank

### ISSUE THREAD

**Issue by raseals** [teelolws/Altoholic-Retail#130]
Just installed Altoholic-Retail 9.0.1-009 (first time user - have not touched any settings), with multiple reloads and game restarts. I have logged into many characters on the same server, and same faction. I have opened bank inventory on each character and inventory bags. I have opened and clicked on each guild bank tab.

Issue is that when I try and search for items using Altoholic menu, does not find items in the guild bank.
Another issue, when I hover over an item in my inventory or bank, the tooltip does not show details about any item that does exist in the guild bank, but I can see the item and how many exists on each character.

Using the Altoholic-Retail 'in-game' menu, I can click on the Guild tab and see all the items in my guild bank, just can't find them when searching or the count.

**Comment by teelolws** [comment]
Check this option: "Hide this guild in the tooltip"

![image](https://user-images.githubusercontent.com/49792789/96301693-07421280-1054-11eb-943a-9e778254e283.png)

**Comment by raseals** [comment]
The tooltip is not working when I put my mouse on top of the guild button. You can't tell by the image I uploaded, but my cursor is right on top of the "Guild Members" button (or what looks like images of people. The other buttons have tool tips, just not the first button.

![altoholic-guild-bank](https://user-images.githubusercontent.com/798244/96302571-0e6f0f00-0fc7-11eb-8894-26b343edcc03.png)

**Comment by teelolws** [comment]
Hmm. Can you .zip up and upload your Altoholic and Datastore saved variables? You'll find them in your _retail_/WTF/Account/Account/SavedVariables folder, like this:

![image](https://user-images.githubusercontent.com/49792789/96303431-d9aa9880-1056-11eb-85b6-c7d344ccc6db.png)

**Comment by raseals** [comment]
I sure can, please find the file attached.
Really do appreciate you investigating my issue.
[Altoholic-Datastore-SavedVariables.zip](https://github.com/teelolws/Altoholic-Retail/files/5394430/Altoholic-Datastore-SavedVariables.zip)

**Comment by teelolws** [comment]
Allright, so this was a problem with your guild not being on the same server as your characters. The UI was designed before that was possible, so it was never considered.

Its now fixed in: https://github.com/teelolws/Altoholic-Retail/commit/20159e8f93a60fe05e959c6751f03e8a6b048a8a

I won't be able to release this update for a while, so if you want it now, just get that file Altoholic_Guild\Templates\GuildBankIcon.lua from the repository.

**Comment by teelolws** [comment]
Whoops, left some debugging code in there: https://github.com/teelolws/Altoholic-Retail/commit/8efe304f06697ae1d11a0e4d880402ac4fba1e4b

**Comment by raseals** [comment]
Since I am also a software dev, mainly Java, I am completely familiar with
GitHub.

I cloned your master repo and verified that the change you made was in the
master branch.

I copied the file from the repo:
Altoholic_Guild\Templates\GuildBankIcon.lua and copied it to: E:\World of
Warcraft\_retail_\Interface\AddOns\Altoholic_Guild\Templates

I made a backup copy of the file first, then started the game, and I
immediately went to Altoholic client and I wanted to report that it is
still not working.

I move the mouse over the Guild Icon and nothing happens.

**Comment by teelolws** [comment]
Found a possible fix: https://github.com/teelolws/Altoholic-Retail/commit/b2c36a6c6303dc385f1ed6715a432e7bd12b3786 and https://github.com/teelolws/DataStore_Containers/commit/697893a30db3b7c8bf68a6178ae39d360bf92d60

Can you try the latest beta. https://github.com/teelolws/Altoholic-Retail/releases/tag/9.0.1-010-BETA-2

**Comment by raseals** [comment]
I installed the BETA version. I can now see the tooltips on the Guild tab
when I hover over the Guild icon.

However, I still can't see guild summary data from the summary screen.
I still cannot search for items that exist in the guild bank. I'm search
for "light leather".

I am able to see all the items exist when I am on the Guild tab and view
each bag. Just can't view them.

As far as options go on the tooltip, I have selected on "Bonechewer - Ashen
Wolves":

* Show this guild's realm in the tooltip
* Include this guild's gold in the summary totals

Attached are some images:

- Guild tooltip options
- Search results "light leather"
- Summary tab

Thanks for all your help and assistance.

**Comment by teelolws** [comment]
If you want to include images you'll need to open the Github issue page and attach them there

**Comment by raseals** [comment]
![altoholic-BETA-search](https://user-images.githubusercontent.com/798244/96364157-5301c400-1107-11eb-9284-607e6d67e8e7.png)
![altoholic-BETA-summary](https://user-images.githubusercontent.com/798244/96364158-5301c400-1107-11eb-94a7-b044af3906a0.png)
![altoholic-BETA-guild-bank](https://user-images.githubusercontent.com/798244/96364159-539a5a80-1107-11eb-913f-7f5a4c488bcc.png)

**Comment by teelolws** [comment]
Its probably a problem with the guild being on a different server, but to be sure, can you show me your tooltip and search settings:

![image](https://user-images.githubusercontent.com/49792789/96364592-bc311800-1197-11eb-85eb-4a619c5bdb01.png)

and

![image](https://user-images.githubusercontent.com/49792789/96364596-c3582600-1197-11eb-8597-1d0d7d758086.png)

**Comment by raseals** [comment]
![altoholic-BETA-interface-tooltip](https://user-images.githubusercontent.com/798244/96364950-5c8d2b00-110b-11eb-9766-3eac0341fdc5.png)
![altoholic-BETA-interface-search](https://user-images.githubusercontent.com/798244/96364951-5d25c180-110b-11eb-83e2-bd91203ed264.png)

**Comment by teelolws** [comment]
These two should solve the tooltip problems:

https://github.com/teelolws/DataStore_Characters/commit/ee5ef0f0c585b9e1a42b1bfae60575d06a9800a6
and
https://github.com/teelolws/Altoholic-Retail/commit/41e251b2ffb7ca87dc28a4447bbadf874ad507f8

For my character here, the guild is on a different server:
![image](https://user-images.githubusercontent.com/49792789/96385433-70f72380-11f0-11eb-9464-466473c076b3.png)

I'll work on the Search tab next.

**Comment by teelolws** [comment]
And this should fix the search tab: 

![image](https://user-images.githubusercontent.com/49792789/96385672-e9aaaf80-11f1-11eb-9791-922fd3d17649.png)

You'll need the search location to include "All Realms" or "All Accounts" for it to work. Search tab doesn't support connected realms.
![image](https://user-images.githubusercontent.com/49792789/96385698-0e9f2280-11f2-11eb-9793-363a8e118907.png)

Try this beta: https://github.com/teelolws/Altoholic-Retail/releases/tag/9.0.1-010-BETA-C

**Comment by raseals** [comment]
It is all working now. Changed to "all realms" in the search location and I
am able to find items.

Thank you so much for your diligence in investigating and fixing the
problem. Very much appreciated!

**Comment by teelolws** [comment]
Great to hear!
